# CPE 486/586: Machine Learning for Engineering Applications
## Instructor and Author of this notebook: Rahul Bhadani

# Basic Linear Algebra in PyTorch

In [3]:
import torch
import numpy as np
from torch import linalg as LA

# VECTORS - BASIC OPERATIONS

## Column Vector Creation

In [ ]:

print("Column Vectors:")
v_col = torch.tensor([[1], [2], [3]], dtype=torch.float32)
print(f"Column vector v: \n{v_col}")
print(f"Shape: {v_col.shape}")

## Row Vectors

In [ ]:
print("\nRow Vectors:")
v_row = torch.tensor([[1, 2, 3]], dtype=torch.float32)
print(f"Row vector v: \n{v_row}")
print(f"Shape: {v_row.shape}")

## 1D Vector

In [4]:
print("\n1D Vectors (No row/column distinction):")
v_1d = torch.tensor([1, 2, 3], dtype=torch.float32)
print(f"1D vector v: {v_1d}")
print(f"Shape: {v_1d.shape}")


1D Vectors (No row/column distinction):
1D vector v: tensor([1., 2., 3.])
Shape: torch.Size([3])


# VECTOR OPERATIONS

## Elementwise Vector Multiplication


In [5]:
print("Elementwise Vector Multiplication:")
v = torch.tensor([[1], [2], [3]], dtype=torch.float32)
w = torch.tensor([[3], [4], [5]], dtype=torch.float32)
u_elementwise = v * w
print(f"v = \n{v}")
print(f"w = \n{w}")
print(f"v * w (elementwise) = \n{u_elementwise}")

Elementwise Vector Multiplication:
v = 
tensor([[1.],
        [2.],
        [3.]])
w = 
tensor([[3.],
        [4.],
        [5.]])
v * w (elementwise) = 
tensor([[ 3.],
        [ 8.],
        [15.]])


## Vector Dot Product

In [6]:
print("\nVector Dot Product:")
v_1d = torch.tensor([1, 2, 3], dtype=torch.float32)
w_1d = torch.tensor([3, 4, 5], dtype=torch.float32)
dot_product = torch.dot(v_1d, w_1d)
print(f"v = {v_1d}")
print(f"w = {w_1d}")
print(f"v · w = {dot_product}")



Vector Dot Product:
v = tensor([1., 2., 3.])
w = tensor([3., 4., 5.])
v · w = 26.0


## Dot product using matrix multiplication

In [7]:
dot_product_alt = v.T @ w
print(f"v^T @ w = {dot_product_alt}")

v^T @ w = tensor([[26.]])


## Vector Norms

In [9]:
v = torch.tensor([1, 2, 3], dtype=torch.float32)
print(f"Vector v = {v}")

l1_norm = torch.norm(v, p=1)
print(f"L1 norm (Manhattan): ||v||_1 = {l1_norm}")

# L2 Norm (Euclidean Norm)
l2_norm = torch.norm(v, p=2)  # or simply torch.norm(v)
print(f"L2 norm (Euclidean): ||v||_2 = {l2_norm}")

max_norm = torch.norm(v, p=float('inf'))
print(f"Max norm (Infinity): ||v||_∞ = {max_norm}")

Vector v = tensor([1., 2., 3.])
L1 norm (Manhattan): ||v||_1 = 6.0
L2 norm (Euclidean): ||v||_2 = 3.7416574954986572
Max norm (Infinity): ||v||_∞ = 3.0


# VECTOR BROADCASTING

## Row + Column broadcasting

In [10]:
v_row = torch.tensor([[1, 5, 6]], dtype=torch.float32)  # 1x3
w_col = torch.tensor([[10], [20], [30]], dtype=torch.float32)  # 3x1
result = v_row + w_col
print(f"Row vector (1x3): {v_row}")
print(f"Column vector (3x1): \n{w_col}")
print(f"Broadcasting result (3x3): \n{result}")

Row vector (1x3): tensor([[1., 5., 6.]])
Column vector (3x1): 
tensor([[10.],
        [20.],
        [30.]])
Broadcasting result (3x3): 
tensor([[11., 15., 16.],
        [21., 25., 26.],
        [31., 35., 36.]])


## Example 2

In [11]:
print("\nBroadcasting Example 2:")
v_col = torch.tensor([[1], [2], [3]], dtype=torch.float32)  # 3x1
w_row = torch.tensor([[10, 20]], dtype=torch.float32)  # 1x2
result2 = v_col + w_row
print(f"Column vector (3x1): \n{v_col}")
print(f"Row vector (1x2): {w_row}")
print(f"Broadcasting result (3x2): \n{result2}")


Broadcasting Example 2:
Column vector (3x1): 
tensor([[1.],
        [2.],
        [3.]])
Row vector (1x2): tensor([[10., 20.]])
Broadcasting result (3x2): 
tensor([[11., 21.],
        [12., 22.],
        [13., 23.]])


# Matrices

## Rectangular Matrix

In [12]:

print("Rectangular Matrix:")
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(f"Matrix A: \n{A}")
print(f"Shape: {A.shape}")

Rectangular Matrix:
Matrix A: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3])


## Hadamard Product (Elementwise Multiplication)

In [13]:
print("Hadamard Product (Elementwise):")
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
B = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
C_hadamard = A * B
print(f"A = \n{A}")
print(f"B = \n{B}")
print(f"A ∘ B (Hadamard) = \n{C_hadamard}")

Hadamard Product (Elementwise):
A = 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
B = 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
A ∘ B (Hadamard) = 
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


## Matrix-Matrix Multiplication

In [14]:
print("\nMatrix-Matrix Multiplication:")
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
C_matmul = torch.matmul(A, B)  # or A @ B
print(f"A = \n{A}")
print(f"B = \n{B}")
print(f"A @ B = \n{C_matmul}")



Matrix-Matrix Multiplication:
A = 
tensor([[1., 2.],
        [3., 4.]])
B = 
tensor([[5., 6.],
        [7., 8.]])
A @ B = 
tensor([[19., 22.],
        [43., 50.]])


## Upper Triangular Matrix


In [15]:
print("Upper Triangular Matrix:")
A_upper = torch.tensor([[1, 2, 3], [0, 4, 5], [0, 0, 6]], dtype=torch.float32)
print(f"Upper triangular A = \n{A_upper}")

Upper Triangular Matrix:
Upper triangular A = 
tensor([[1., 2., 3.],
        [0., 4., 5.],
        [0., 0., 6.]])


## Lower Triangular Matrix

In [16]:
print("\nLower Triangular Matrix:")
B_lower = torch.tensor([[1, 0, 0], [4, 5, 0], [7, 8, 9]], dtype=torch.float32)
print(f"Lower triangular B = \n{B_lower}")


Lower Triangular Matrix:
Lower triangular B = 
tensor([[1., 0., 0.],
        [4., 5., 0.],
        [7., 8., 9.]])


## Identity Matrix

In [17]:
print("\nIdentity Matrix:")
I = torch.eye(3)
print(f"3x3 Identity matrix I = \n{I}")


Identity Matrix:
3x3 Identity matrix I = 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Diagonal Matrix

In [18]:
print("\nDiagonal Matrix:")
D = torch.diag(torch.tensor([1, 2, 3], dtype=torch.float32))
print(f"Diagonal matrix D = \n{D}")



Diagonal Matrix:
Diagonal matrix D = 
tensor([[1., 0., 0.],
        [0., 2., 0.],
        [0., 0., 3.]])


## Orthogonal Matrix

In [19]:
Q = torch.tensor([[1, 0], [0, -1]], dtype=torch.float32)
Q_transpose = Q.T
Q_inverse = torch.inverse(Q)
print(f"Q = \n{Q}")
print(f"Q^T = \n{Q_transpose}")
print(f"Q^(-1) = \n{Q_inverse}")
print(f"Q @ Q^T = \n{Q @ Q_transpose}")  # Should be identity

Q = 
tensor([[ 1.,  0.],
        [ 0., -1.]])
Q^T = 
tensor([[ 1.,  0.],
        [ 0., -1.]])
Q^(-1) = 
tensor([[ 1.,  0.],
        [-0., -1.]])
Q @ Q^T = 
tensor([[1., 0.],
        [0., 1.]])


## Transpose

In [20]:
print("Matrix Transpose:")
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
A_transpose = A.T
print(f"A = \n{A}")
print(f"A^T = \n{A_transpose}")

Matrix Transpose:
A = 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
A^T = 
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Determinant

In [21]:
print("\nMatrix Determinant:")
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
det_A = torch.det(A)
print(f"A = \n{A}")
print(f"det(A) = {det_A}")


Matrix Determinant:
A = 
tensor([[1., 2.],
        [3., 4.]])
det(A) = -2.0


## Matrix Inverse

In [22]:
print("\nMatrix Inverse:")
A = torch.tensor([[4, 7], [2, 6]], dtype=torch.float32)
A_inv = torch.inverse(A)
print(f"A = \n{A}")
print(f"A^(-1) = \n{A_inv}")
print(f"A @ A^(-1) = \n{A @ A_inv}")  # Should be close to identity


Matrix Inverse:
A = 
tensor([[4., 7.],
        [2., 6.]])
A^(-1) = 
tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])
A @ A^(-1) = 
tensor([[1., 0.],
        [0., 1.]])


## Trace

In [23]:
# Trace
print("\nMatrix Trace:")
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
trace_A = torch.trace(A)
print(f"A = \n{A}")
print(f"tr(A) = {trace_A}")



Matrix Trace:
A = 
tensor([[1., 2.],
        [3., 4.]])
tr(A) = 5.0


## Rank

In [24]:
print("\nMatrix Rank:")
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
rank_A = torch.linalg.matrix_rank(A)
print(f"A = \n{A}")
print(f"rank(A) = {rank_A}")


Matrix Rank:
A = 
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
rank(A) = 2


# SYSTEM OF LINEAR EQUATIONS

## Example system: AX = B

In [ ]:
print("System of Linear Equations: AX = B")

# Coefficient matrix A and constant vector B
A = torch.tensor([[2, 3, 5], 
                    [4, -2, -7], 
                    [9, 5, -3]], dtype=torch.float32)
B = torch.tensor([[1], [8], [2]], dtype=torch.float32)

print(f"Coefficient matrix A = \n{A}")
print(f"Constants vector B = \n{B}")

System of Linear Equations: AX = B
Coefficient matrix A = 
tensor([[ 2.,  3.,  5.],
        [ 4., -2., -7.],
        [ 9.,  5., -3.]])
Constants vector B = 
tensor([[1.],
        [8.],
        [2.]])


##  Method 1: Using matrix inverse

In [27]:
print("\nMethod 1: Using Matrix Inverse (X = A^(-1) * B):")
try:
    A_inv = torch.inverse(A)
    X_inverse = A_inv @ B
    print(f"A^(-1) = \n{A_inv}")
    print(f"Solution X = A^(-1) @ B = \n{X_inverse}")
    
    # Verification
    verification = A @ X_inverse
    print(f"Verification: A @ X = \n{verification}")
    print(f"Should equal B = \n{B}")
except:
    print("Matrix is singular (non-invertible)")


Method 1: Using Matrix Inverse (X = A^(-1) * B):
A^(-1) = 
tensor([[ 0.3445,  0.2857, -0.0924],
        [-0.4286, -0.4286,  0.2857],
        [ 0.3193,  0.1429, -0.1345]])
Solution X = A^(-1) @ B = 
tensor([[ 2.4454],
        [-3.2857],
        [ 1.1933]])
Verification: A @ X = 
tensor([[1.0000],
        [8.0000],
        [2.0000]])
Should equal B = 
tensor([[1.],
        [8.],
        [2.]])


## Method 2: Using torch.linalg.solve (more numerically stable)

In [28]:
print("\nMethod 2: Using torch.linalg.solve:")
X_solve = torch.linalg.solve(A, B)
print(f"Solution X = \n{X_solve}")

# Verification
verification_solve = A @ X_solve
print(f"Verification: A @ X = \n{verification_solve}")


Method 2: Using torch.linalg.solve:
Solution X = 
tensor([[ 2.4454],
        [-3.2857],
        [ 1.1933]])
Verification: A @ X = 
tensor([[1.0000],
        [8.0000],
        [2.0000]])


## Gaussian Elimination Step by Step

In [29]:

print("Starting with augmented matrix [A|B]:")
# Create augmented matrix for the system
A_orig = torch.tensor([[2, 3, 5], 
                       [4, -2, -7], 
                       [9, 5, -3]], dtype=torch.float32)
B_orig = torch.tensor([[1], [8], [2]], dtype=torch.float32)

# Create augmented matrix
augmented = torch.cat([A_orig, B_orig], dim=1)
print(f"Augmented matrix = \n{augmented}")

# Manual Gaussian elimination steps (simplified version)
print("\nStep 1: Scale first row to get pivot = 1")
augmented[0] = augmented[0] / augmented[0, 0]
print(f"After scaling R1 by 1/2: \n{augmented}")

print("\nStep 2: Eliminate below first pivot")
augmented[1] = augmented[1] - 4 * augmented[0]
augmented[2] = augmented[2] - 9 * augmented[0]
print(f"After eliminating below pivot: \n{augmented}")

print("\nStep 3: Scale second row to get pivot = 1")
augmented[1] = augmented[1] / augmented[1, 1]
print(f"After scaling R2: \n{augmented}")

print("\nStep 4: Eliminate below second pivot")
augmented[2] = augmented[2] - augmented[2, 1] * augmented[1]
print(f"After eliminating below second pivot: \n{augmented}")

print("\nStep 5: Scale third row to get pivot = 1")
augmented[2] = augmented[2] / augmented[2, 2]
print(f"Final REF form: \n{augmented}")

# Extract solution using back-substitution
x3 = augmented[2, 3]
x2 = augmented[1, 3] - augmented[1, 2] * x3
x1 = augmented[0, 3] - augmented[0, 2] * x3 - augmented[0, 1] * x2

print(f"\nBack-substitution solution:")
print(f"x3 = {x3}")
print(f"x2 = {x2}")
print(f"x1 = {x1}")
print(f"Solution vector: [{x1}, {x2}, {x3}]")

Starting with augmented matrix [A|B]:
Augmented matrix = 
tensor([[ 2.,  3.,  5.,  1.],
        [ 4., -2., -7.,  8.],
        [ 9.,  5., -3.,  2.]])

Step 1: Scale first row to get pivot = 1
After scaling R1 by 1/2: 
tensor([[ 1.0000,  1.5000,  2.5000,  0.5000],
        [ 4.0000, -2.0000, -7.0000,  8.0000],
        [ 9.0000,  5.0000, -3.0000,  2.0000]])

Step 2: Eliminate below first pivot
After eliminating below pivot: 
tensor([[  1.0000,   1.5000,   2.5000,   0.5000],
        [  0.0000,  -8.0000, -17.0000,   6.0000],
        [  0.0000,  -8.5000, -25.5000,  -2.5000]])

Step 3: Scale second row to get pivot = 1
After scaling R2: 
tensor([[  1.0000,   1.5000,   2.5000,   0.5000],
        [ -0.0000,   1.0000,   2.1250,  -0.7500],
        [  0.0000,  -8.5000, -25.5000,  -2.5000]])

Step 4: Eliminate below second pivot
After eliminating below second pivot: 
tensor([[ 1.0000,  1.5000,  2.5000,  0.5000],
        [-0.0000,  1.0000,  2.1250, -0.7500],
        [ 0.0000,  0.0000, -7.4375, -8.875

## Linear Independence

In [30]:
# Example 1: Linearly independent vectors
print("Example 1: Testing linear independence")
v1 = torch.tensor([1, 2], dtype=torch.float32)
v2 = torch.tensor([2, 3], dtype=torch.float32)

# Create matrix with vectors as columns
vectors_matrix = torch.stack([v1, v2], dim=1)
print(f"Matrix with vectors as columns: \n{vectors_matrix}")

# Check determinant (for square matrices)
det_vectors = torch.det(vectors_matrix)
print(f"Determinant: {det_vectors}")
print(f"Linearly independent? {abs(det_vectors) > 1e-6}")

Example 1: Testing linear independence
Matrix with vectors as columns: 
tensor([[1., 2.],
        [2., 3.]])
Determinant: -1.0
Linearly independent? True


In [31]:
# Example 2: Linearly dependent vectors
print("\nExample 2: Linearly dependent vectors")
v3 = torch.tensor([1, 2], dtype=torch.float32)
v4 = torch.tensor([2, 4], dtype=torch.float32)  # v4 = 2 * v3

dependent_matrix = torch.stack([v3, v4], dim=1)
print(f"Matrix with dependent vectors: \n{dependent_matrix}")

det_dependent = torch.det(dependent_matrix)
print(f"Determinant: {det_dependent}")
print(f"Linearly independent? {abs(det_dependent) > 1e-6}")


Example 2: Linearly dependent vectors
Matrix with dependent vectors: 
tensor([[1., 2.],
        [2., 4.]])
Determinant: -0.0
Linearly independent? False


## Basis and Dimensions

In [32]:
print("Standard basis for R^3:")
e1 = torch.tensor([1, 0, 0], dtype=torch.float32)
e2 = torch.tensor([0, 1, 0], dtype=torch.float32)
e3 = torch.tensor([0, 0, 1], dtype=torch.float32)

standard_basis = torch.stack([e1, e2, e3], dim=1)
print(f"Standard basis matrix: \n{standard_basis}")

# Express a vector in terms of standard basis
x = torch.tensor([5, 3, -2], dtype=torch.float32)
print(f"\nVector x = {x}")
print(f"x = {x[0]}*e1 + {x[1]}*e2 + {x[2]}*e3")
print(f"x = {x[0]}*{e1} + {x[1]}*{e2} + {x[2]}*{e3}")

# Verify
reconstructed = x[0]*e1 + x[1]*e2 + x[2]*e3
print(f"Reconstructed vector: {reconstructed}")
print(f"Original == Reconstructed? {torch.allclose(x, reconstructed)}")


Standard basis for R^3:
Standard basis matrix: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Vector x = tensor([ 5.,  3., -2.])
x = 5.0*e1 + 3.0*e2 + -2.0*e3
x = 5.0*tensor([1., 0., 0.]) + 3.0*tensor([0., 1., 0.]) + -2.0*tensor([0., 0., 1.])
Reconstructed vector: tensor([ 5.,  3., -2.])
Original == Reconstructed? True


# Eigenvector and Eigenvalues

## Numpy Implementation

In [ ]:
import numpy as np

# Define a 2x2 matrix
A = np.array([[4, 1],
                [2, 3]])

# Compute eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(A)

print("Eigenvalues:", eigenvals)
print("Eigenvectors:")
print(eigenvecs)

Eigenvalues: [5. 2.]
Eigenvectors:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


## PyTorch Implementation

In [1]:
import torch

# Create a matrix
A = torch.tensor([[4.0, 1.0],
                [2.0, 3.0]], dtype=torch.float32)

# Compute eigenvalues and eigenvectors
eigenvals, eigenvecs = torch.linalg.eig(A)

print("Matrix A:")
print(A)
print("Eigenvalues:", eigenvals)
print("Eigenvectors:")
print(eigenvecs)

Matrix A:
tensor([[4., 1.],
        [2., 3.]])
Eigenvalues: tensor([5.0000+0.j, 2.0000+0.j])
Eigenvectors:
tensor([[ 0.7071+0.j, -0.4472+0.j],
        [ 0.7071+0.j,  0.8944+0.j]])


In [4]:
# Matrix with gradient tracking
A = torch.tensor([[4.0, 1.0],
                [2.0, 3.0]], requires_grad=True)
# Compute largest eigenvalue
eigenvals, _ = torch.linalg.eigh(A)
largest_eigenval = eigenvals[-1]
# Backpropagation
largest_eigenval.backward()
print("Gradient of largest eigenvalue:")
print(A.grad)

Gradient of largest eigenvalue:
tensor([[0.6213, 0.4851],
        [0.4851, 0.3787]])
